# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    image: 'search-query-builder-master-api'
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase?schema=public
    restart: always
    ports:
      - 3000:3000

  web:
    image: 'search-query-builder-master-web'
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - VITE_TECHONOLOGIES_API=${VITE_TECHONOLOGIES_API}
    ports:
      - '3001:3001'
    environment:
      - VITE_TECHONOLOGIES_API=http://backend:3000

volumes:
  postgres_data:
